export const LANGUAGES = [
    {"label": "Abkhazian", "value": "abk"},
    {"label": "Afar", "value": "aar"},
    {"label": "Afrikaans", "value": "afr"},
    {"label": "Akan", "value": "aka"},
    {"label": "Albanian", "value": "alb"},
    {"label": "Amharic", "value": "amh"},
    {"label": "Arabic", "value": "ara"},
    {"label": "Aragonese", "value": "arg"},
    {"label": "Armenian", "value": "arm"},
    {"label": "Assamese", "value": "asm"},
    {"label": "Avaric", "value": "ava"},
    {"label": "Avestan", "value": "ave"},
    {"label": "Aymara", "value": "aym"},
    {"label": "Azerbaijani", "value": "aze"},
    {"label": "Bambara", "value": "bam"},
    {"label": "Bashkir", "value": "bak"},
    {"label": "Basque", "value": "baq"},
    {"label": "Belarusian", "value": "bel"},
    {"label": "Bengali", "value": "ben"},
    {"label": "Bislama", "value": "bis"},
    {"label": "Bosnian", "value": "bos"},
    {"label": "Breton", "value": "bre"},
    {"label": "Bulgarian", "value": "bul"},
    {"label": "Burmese", "value": "bur"},
    {"label": "Catalan, Valencian", "value": "cat"},
    {"label": "Chamorro", "value": "cha"},
    {"label": "Chechen", "value": "che"},
    {"label": "Chichewa, Chewa, Nyanja", "value": "nya"},
    {"label": "Chinese", "value": "chi"},
    // {"label": "Church Slavonic, Old Slavonic, Old Church Slavonic", "value": "chu"},
    {"label": "Chuvash", "value": "chv"},
    {"label": "Cornish", "value": "cor"},
    {"label": "Corsican", "value": "cos"},
    {"label": "Cree", "value": "cre"},
    {"label": "Croatian", "value": "hrv"},
    {"label": "Czech", "value": "cze"},
    {"label": "Danish", "value": "dan"},
    {"label": "Divehi, Dhivehi, Maldivian", "value": "div"},
    {"label": "Dutch, Flemish", "value": "dut"},
    {"label": "Dzongkha", "value": "dzo"},
    {"label": "English", "value": "eng"},
    {"label": "Esperanto", "value": "epo"},
    {"label": "Estonian", "value": "est"},
    {"label": "Ewe", "value": "ewe"},
    {"label": "Faroese", "value": "fao"},
    {"label": "Fijian", "value": "fij"},
    {"label": "Finnish", "value": "fin"},
    {"label": "French", "value": "fre"},
    {"label": "Western Frisian", "value": "fry"},
    {"label": "Fulah", "value": "ful"},
    {"label": "Gaelic, Scottish Gaelic", "value": "gla"},
    {"label": "Galician", "value": "glg"},
    {"label": "Ganda", "value": "lug"},
    {"label": "Georgian", "value": "geo"},
    {"label": "German", "value": "ger"},
    {"label": "Greek, Modern (1453–)", "value": "gre"},
    {"label": "Kalaallisut, Greenlandic", "value": "kal"},
    {"label": "Guarani", "value": "grn"},
    {"label": "Gujarati", "value": "guj"},
    {"label": "Haitian, Haitian Creole", "value": "hat"},
    {"label": "Hausa", "value": "hau"},
    {"label": "Hebrew", "value": "heb"},
    {"label": "Herero", "value": "her"},
    {"label": "Hindi", "value": "hin"},
    {"label": "Hiri Motu", "value": "hmo"},
    {"label": "Hungarian", "value": "hun"},
    {"label": "Icelandic", "value": "ice"},
    {"label": "Ido", "value": "ido"},
    {"label": "Igbo", "value": "ibo"},
    {"label": "Indonesian", "value": "ind"},
    {"label": "Interlingua (International Auxiliary Language Association)", "value": "ina"},
    {"label": "Interlingue, Occidental", "value": "ile"},
    {"label": "Inuktitut", "value": "iku"},
    {"label": "Inupiaq", "value": "ipk"},
    {"label": "Irish", "value": "gle"},
    {"label": "Italian", "value": "ita"},
    {"label": "Japanese", "value": "jpn"},
    {"label": "Javanese", "value": "jav"},
    {"label": "Kannada", "value": "kan"},
    {"label": "Kanuri", "value": "kau"},
    {"label": "Kashmiri", "value": "kas"},
    {"label": "Kazakh", "value": "kaz"},
    {"label": "Central Khmer", "value": "khm"},
    {"label": "Kikuyu, Gikuyu", "value": "kik"},
    {"label": "Kinyarwanda", "value": "kin"},
    {"label": "Kirghiz, Kyrgyz", "value": "kir"},
    {"label": "Komi", "value": "kom"},
    {"label": "Kongo", "value": "kon"},
    {"label": "Korean", "value": "kor"},
    {"label": "Kuanyama, Kwanyama", "value": "kua"},
    {"label": "Kurdish", "value": "kur"},
    {"label": "Lao", "value": "lao"},
    {"label": "Latin", "value": "lat"},
    {"label": "Latvian", "value": "lav"},
    {"label": "Limburgan, Limburger, Limburgish", "value": "lim"},
    {"label": "Lingala", "value": "lin"},
    {"label": "Lithuanian", "value": "lit"},
    {"label": "Luba-Katanga", "value": "lub"},
    {"label": "Luxembourgish, Letzeburgesch", "value": "ltz"},
    {"label": "Macedonian", "value": "mac"},
    {"label": "Malagasy", "value": "mlg"},
    {"label": "Malay", "value": "may"},
    {"label": "Malayalam", "value": "mal"},
    {"label": "Maltese", "value": "mlt"},
    {"label": "Manx", "value": "glv"},
    {"label": "Maori", "value": "mao"},
    {"label": "Marathi", "value": "mar"},
    {"label": "Marshallese", "value": "mah"},
    {"label": "Mongolian", "value": "mon"},
    {"label": "Nauru", "value": "nau"},
    {"label": "Navajo, Navaho", "value": "nav"},
    {"label": "North Ndebele", "value": "nde"},
    {"label": "South Ndebele", "value": "nbl"},
    {"label": "Ndonga", "value": "ndo"},
    {"label": "Nepali", "value": "nep"},
    {"label": "Norwegian", "value": "nor"},
    {"label": "Norwegian Bokmål", "value": "nob"},
    {"label": "Norwegian Nynorsk", "value": "nno"},
    {"label": "Sichuan Yi, Nuosu", "value": "iii"},
    {"label": "Occitan", "value": "oci"},
    {"label": "Ojibwa", "value": "oji"},
    {"label": "Oriya", "value": "ori"},
    {"label": "Oromo", "value": "orm"},
    {"label": "Ossetian, Ossetic", "value": "oss"},
    {"label": "Pali", "value": "pli"},
    {"label": "Pashto, Pushto", "value": "pus"},
    {"label": "Persian", "value": "per"},
    {"label": "Polish", "value": "pol"},
    {"label": "Portuguese", "value": "por"},
    {"label": "Punjabi, Panjabi", "value": "pan"},
    {"label": "Quechua", "value": "que"},
    {"label": "Romanian, Moldavian, Moldovan", "value": "rum"},
    {"label": "Romansh", "value": "roh"},
    {"label": "Rundi", "value": "run"},
    {"label": "Russian", "value": "rus"},
    {"label": "Northern Sami", "value": "sme"},
    {"label": "Samoan", "value": "smo"},
    {"label": "Sango", "value": "sag"},
    {"label": "Sanskrit", "value": "san"},
    {"label": "Sardinian", "value": "srd"},
    {"label": "Serbian", "value": "srp"},
    {"label": "Shona", "value": "sna"},
    {"label": "Sindhi", "value": "snd"},
    {"label": "Sinhala, Sinhalese", "value": "sin"},
    {"label": "Slovak", "value": "slo"},
    {"label": "Slovenian", "value": "slv"},
    {"label": "Somali", "value": "som"},
    {"label": "Southern Sotho", "value": "sot"},
    {"label": "Spanish, Castilian", "value": "spa"},
    {"label": "Sundanese", "value": "sun"},
    {"label": "Swahili", "value": "swa"},
    {"label": "Swati", "value": "ssw"},
    {"label": "Swedish", "value": "swe"},
    {"label": "Tagalog", "value": "tgl"},
    {"label": "Tahitian", "value": "tah"},
    {"label": "Tajik", "value": "tgk"},
    {"label": "Tamil", "value": "tam"},
    {"label": "Tatar", "value": "tat"},
    {"label": "Telugu", "value": "tel"},
    {"label": "Thai", "value": "tha"},
    {"label": "Tibetan", "value": "tib"},
    {"label": "Tigrinya", "value": "tir"},
    {"label": "Tonga (Tonga Islands)", "value": "ton"},
    {"label": "Tsonga", "value": "tso"},
    {"label": "Tswana", "value": "tsn"},
    {"label": "Turkish", "value": "tur"},
    {"label": "Turkmen", "value": "tuk"},
    {"label": "Twi", "value": "twi"},
    {"label": "Uighur, Uyghur", "value": "uig"},
    {"label": "Ukrainian", "value": "ukr"},
    {"label": "Urdu", "value": "urd"},
    {"label": "Uzbek", "value": "uzb"},
    {"label": "Venda", "value": "ven"},
    {"label": "Vietnamese", "value": "vie"},
    {"label": "Volapük", "value": "vol"},
    {"label": "Walloon", "value": "wln"},
    {"label": "Welsh", "value": "wel"},
    {"label": "Wolof", "value": "wol"},
    {"label": "Xhosa", "value": "xho"},
    {"label": "Yiddish", "value": "yid"},
    {"label": "Yoruba", "value": "yor"},
    {"label": "Zhuang, Chuang", "value": "zha"},
    {"label": "Zulu", "value": "zul"},
]